creacion action e iac

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,8 +6,8 @@ on:
         - main
         - dgracili
 env:
-  AWS_REGION: us-east-1
-  TF_VERSION: 1.13.1
+  AWS_REGION: 'us-east-1'
+  TF_VERSION: ''
 
 jobs:
   terraform:
@@ -24,8 +24,7 @@ jobs:
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: ${{ env.TF_VERSION }}
-        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
-
+       
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
@@ -36,21 +35,43 @@ jobs:
     - name: Terraform Init
       run: terraform init
 
+      #Validate IaC in terraform
     - name: Terraform Format
       id: format
-      run: terraform fmt 
+      run: terraform fmt -check -recursive
 
     - name: Terraform Validate
       id: validate
       run: terraform validate -no-color
     
-    - name: Run Checkov
+      #Validate static code in IaC
+    - name: Checkov Scan
       id: checkov
       uses: bridgecrewio/checkov-action@v12
       with:
         directory: . 
-        framework: terraform 
-      continue-on-error: false 
+        framework: terraform
+        soft_fail: true  
+        output_format: json 
+        output_file_path: checkov_results.json
+    
+    # - name: Check for Critical Findings
+    #   id: check_critical
+    #   run: |
+    #     critical_count=$(jq '.results.failed_checks | map(select(.severity=="CRITICAL")) | length' checkov_results.json)
+    #     high_count=$(jq '.results.failed_checks | map(select(.severity=="HIGH")) | length' checkov_results.json)
+          
+    #     echo "Vulnerabilidades críticas: $critical_count"
+    #     echo "Vulnerabilidades altas: $high_count"
+
+    #     if [[ $critical_count -gt 0 || $high_count -gt 0 ]]; then
+    #       echo "::error::Se encontraron vulnerabilidades CRÍTICAS o ALTAS. Deteniendo el despliegue."
+    #       exit 1
+    #     fi
+    #   shell: bash
+      env:
+        ACTIONS_STEP_DEBUG: true
+
 
     - name: Terraform Plan
       id: plan
@@ -60,4 +81,5 @@ jobs:
 
     - name: Terraform Apply
       id: apply
+      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       run: terraform apply -auto-approve tfplan
